apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stock-market

resources:
  - stock-service-configmap.yaml
  - stock-service-secret.yaml
  - stock-service-deployment.yaml
  - stock-service-service.yaml
  - stock-service-ingress.yaml
  - stock-service-hpa.yaml