apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stock-market

resources:
  - stock-market-configmap.yaml
  - stock-market-secret.yaml
  - stock-market-deployment.yaml
  - stock-market-service.yaml
  - stock-market-ingress.yaml
  - stock-market-hpa.yaml