apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  namespace: stock-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
        - name: stock-service
          image: manish28/stockservice:v1

          ports:
            - containerPort: 9001

          envFrom:
            - configMapRef:
                name: stock-service-config
            - secretRef:
                name: stock-service-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 1Gi

         