apiVersion: v1
kind: ConfigMap

metadata:
  name: stock-service-config
  namespace: stock-market


data:
  SPRING_PROFILES_ACTIVE: prod
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  REDIS_CLUSTER_NODES: redis:6379
  DB_URL: jdbc:h2:mem:stockdb
  DRIVER_CLASS_NAME: org.h2.Driver

